name: Format

on:
  workflow_call:

jobs:
  format:
    name: Format
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Prettier
        run: npx -y prettier -c .

      - name: Run Shfmt
        run: |
          sudo apt install -y shfmt
          shfmt -d .
