name: Format

on:
  pull_request:

jobs:
  format:
    name: Format

    permissions:
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with: { fetch-depth: 0 }

      - name: Run Prettier
        run: npx -y prettier -c .

      - name: Run Shfmt
        run: |
          sudo apt install -y shfmt
          shfmt -d .
