name: Pull request

on:
  pull_request:

jobs:
  format:
    name: Format
    uses: ./.github/workflows/format.yaml

  test-features:
    name: Test features
    needs: format
    uses: ./.github/workflows/test-features.yaml

  test-images:
    name: Test images
    needs: format
    uses: ./.github/workflows/test-images.yaml

  check:
    name: Check
    if: ${{ always() }}
    needs:
      - format
      - test-features
      - test-images
    runs-on: ubuntu-24.04
    steps:
      - run: exit ${{ (contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) && 1 || 0 }}
