name: Pull request

on:
  pull_request:

jobs:
  format:
    name: Format
    uses: ./.github/workflows/format.yaml

  test-features:
    name: Test features
    needs: format
    uses: ./.github/workflows/test-features.yaml

  test-images-amd64:
    name: Test images (amd64)
    needs: format
    uses: ./.github/workflows/test-images-amd64.yaml

  test-images-arm64:
    name: Test images (arm64)
    needs: format
    uses: ./.github/workflows/test-images-arm64.yaml

  check:
    name: Check
    if: ${{ always() }}
    needs:
      - format
      - test-features
      - test-images-amd64
      - test-images-arm64
    runs-on: ubuntu-24.04
    steps:
      - run: exit ${{ (contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) && 1 || 0 }}
