name: Release image

on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: choice
        options:
          - base
          - devcontainer

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load manifest
        id: manifest
        run: |
          python3 <<EOF >> $GITHUB_OUTPUT

          import json
          from pathlib import Path

          image = Path("images") / "${{ inputs.image }}"
          config = json.loads((image / ".devcontainer" / "devcontainer.json").read_text())
          manifest = config["customizations"]["manifest"]
          name, version = manifest["name"], manifest["version"]
          tags = version.split(".")
          tags = ['.'.join(tags[0:i+1]) for i in range(len(tags))] + ["latest"]

          print(f'tags={", ".join(tags)}')

      - name: Publish images
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/lifadev/devcontainers/${{ inputs.image }}
          imageName: ghcr.io/lifadev/devcontainers/${{ inputs.image }}
          imageTag: ${{ steps.manifest.outputs.tags }}
          platform: linux/amd64,linux/arm64
          push: always
          subFolder: ./images/${{ inputs.image }}
