name: Release images

on:
  pull_request:
    types: [closed]
    paths: ["images/src/**"]

jobs:
  setup:
    name: Setup
    if: github.event.pull_request.merged == true

    permissions:
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with: { fetch-depth: 0 }

      - name: Load config
        id: config
        run: |
          python3 <<EOF >> $GITHUB_OUTPUT

          import json
          from pathlib import Path

          images = [
            image.name
            for image in Path("images/src").iterdir()
            if image.is_dir() and (image / ".devcontainer").is_dir()
          ]

          print(f"images={json.dumps(images)}")
          EOF

    outputs:
      images: ${{ steps.config.outputs.images }}

  release:
    name: Release
    needs: setup

    strategy:
      matrix:
        image: ${{ fromJSON(needs.setup.outputs.images) }}

    uses: ./.github/workflows/release-image.yaml
    with:
      image: ${{ matrix.image }}
