name: Scan

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    name: Scan

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with: { fetch-depth: 0 }

      - name: Run SonarQube
        uses: SonarSource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
