name: Test features

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate matrix
        id: generate-matrix
        run: |
          python3 <<EOF >> $GITHUB_OUTPUT

          import json
          from pathlib import Path

          features = [
            feature.name
            for feature in Path("features/src").iterdir()
            if feature.is_dir()
          ]

          if features:
            print(f'matrix={json.dumps({"feature": features})}')

  test:
    name: Test
    if: ${{ needs.setup.outputs.matrix != '' && toJson(fromJson(needs.setup.outputs.matrix)) != '{}' }}
    needs: setup
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test features
        run: |
          npx -y @devcontainers/cli features test \
            -f ${{ matrix.feature }} \
            --skip-autogenerated \
            --skip-duplicated \
            ./features
