name: Test images

on:
  workflow_call:

jobs:
  setup:
    name: Setup

    permissions:
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Generate matrix
        id: generate-matrix
        run: |
          python3 <<EOF >> $GITHUB_OUTPUT

          import json
          from pathlib import Path

          os = [
            { "name": "ubuntu-24.04", "platform": "linux/amd64" },
            { "name": "ubuntu-24.04-arm", "platform": "linux/arm64" },
          ]

          images = []
          for image in Path("images").iterdir():
            if not image.is_dir(): continue
            config = json.loads((image / ".devcontainer" / "devcontainer.json").read_text())
            manifest = config["customizations"]["manifest"]
            name, version = manifest["name"], manifest["version"]
            tags = version.split(".")
            tags = ['.'.join(tags[0:i+1]) for i in range(len(tags))] + ["latest"]
            images.append({ "name": name, "tags": ", ".join(tags) })

          if images:
            print(f'matrix={json.dumps({"os": os, "image": images})}')

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}

  test:
    name: Test
    if: ${{ needs.setup.outputs.matrix != '' && toJson(fromJson(needs.setup.outputs.matrix)) != '{}' }}
    needs: setup

    permissions:
      contents: read

    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get -y install skopeo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test images
        uses: devcontainers/ci@v0.3
        with:
          platform: ${{ matrix.os.platform }}
          push: never
          subFolder: ./images/${{ matrix.image.name }}
