name: Test image

on:
  workflow_call:
    inputs:
      image: { type: string, required: true }

jobs:
  setup:
    name: Setup

    permissions:
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Load config
        id: config
        env:
          IMAGE: ${{ inputs.image }}
        run: |
          python3 <<EOF >> $GITHUB_OUTPUT

          import json
          from os import environ as env
          from pathlib import Path

          image = Path("images") / env["IMAGE"]
          config = json.loads((image / ".devcontainer" / "devcontainer.json").read_text())
          manifest = config["customizations"]["manifest"]
          name, version = manifest["name"], manifest["version"]

          print(f"version={version}")
          EOF

    outputs:
      version: ${{ steps.config.outputs.version }}

  test:
    name: Test
    needs: setup

    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        os:
          - { name: ubuntu-24.04, arch: amd64 }
          - { name: ubuntu-24.04-arm, arch: arm64 }

    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        env:
          REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          NAMESPACE: ${{ vars.CONTAINER_NAMESPACE_IMAGE }}
          IMAGE: ${{ inputs.image }}
          VERSION: ${{ needs.setup.outputs.version }}
          ARCH: ${{ matrix.os.arch }}
        run: |
          MAJOR="${VERSION%.*.*}"
          MINOR="${VERSION%.*}"

          npx -y @devcontainers/cli build \
            --experimental-lockfile \
            --workspace-folder ./images/$IMAGE \
            --image-name "$REGISTRY/$NAMESPACE/$IMAGE:$VERSION-$ARCH" \
            --cache-from "$REGISTRY/$NAMESPACE/$IMAGE:latest" \
            --cache-from "$REGISTRY/$NAMESPACE/$IMAGE:$MAJOR" \
            --cache-from "$REGISTRY/$NAMESPACE/$IMAGE:$MINOR"
