name: Test feature

on:
  workflow_call:
    inputs:
      feature: { type: string, required: true }

jobs:
  test:
    name: Test

    permissions:
      contents: read
      packages: read

    strategy:
      matrix:
        os:
          - { name: ubuntu-24.04, arch: amd64 }
          - { name: ubuntu-24.04-arm, arch: arm64 }

    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with: { fetch-depth: 0 }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test feature
        env:
          FEATURE: ${{ inputs.feature }}
        run: |
          for _FEATURE in features/src/*; do
            cp \
              ./features/lib/install.sh \
              "$_FEATURE/dev-container-features-install-lib"
          done
          npx -y @devcontainers/cli features test \
            --project-folder ./features \
            --skip-autogenerated \
            --skip-duplicated \
            --features "$FEATURE"
