name: Update feature

on:
  workflow_dispatch:
    inputs:
      feature: { type: string, required: true }

jobs:
  test:
    name: Test

    permissions:
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Update feature
        env:
          FEATURE: ${{ inputs.feature }}
        run: |
          echo "-$FEATURE-"
