name: Update image

on:
  workflow_call:
    inputs:
      image: { type: string, required: true }
    secrets:
      token: { required: true }

jobs:
  update:
    name: Update

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get -y install moreutils uuid

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update image
        id: update
        env:
          GH_TOKEN: ${{ github.token }}
          IMAGE: ${{ inputs.image }}
        run: |
          set -euo pipefail

          git checkout -b "image/$IMAGE/$(uuid -v4 | cut -d- -f2)"

          bash ./images/bin/update.sh "$IMAGE"
          npx -y prettier -w "images/src/$IMAGE"

          if git diff --quiet && git diff --cached --quiet; then
            echo "skip=1" >>$GITHUB_OUTPUT
            exit 0
          fi

          git commit -am "image/$IMAGE: update dependencies"
          git push -u origin HEAD
          echo "skip=0" >>$GITHUB_OUTPUT

      - name: Create pull request
        if: steps.update.outputs.skip == '0'
        env:
          GH_TOKEN: ${{ secrets.token }}
          IMAGE: ${{ inputs.image }}
        run: |
          gh pr create \
            --title "image/$IMAGE: update dependencies" --body "" \
            --base main
